"use client";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <ThemeProvider> */}
      <head />
      <body className="min-h-[800px] ">{children}</body>
      {/* </ThemeProvider> */}
    </html>
  );
}
