"use client" 
import {
  ExclamationTriangleIcon as ErrorIconMini,
  CheckCircleIcon as CheckCircleIconMini,
  EyeIcon as EyeIconMini,
  EyeSlashIcon as EyeSlashIconMini,
  ChevronLeftIcon as ChevronLeftIconMini,
  ArrowUpTrayIcon as ArrowUpTrayIconMini,
  XMarkIcon as XMarkIconMini,
  InformationCircleIcon as InformationCircleIconMini,
  CheckIcon as CheckIconMini,
  PlusIcon as Plus,
  Bars3CenterLeftIcon as MenuBar,
} from "@heroicons/react/20/solid";

import {
  CameraIcon,
  InformationCircleIcon,
  PlusIcon,
  ChevronDownIcon,
  XMarkIcon,
  TrashIcon,
  PencilIcon,
  HomeIcon as Homeicon,
  QuestionMarkCircleIcon as Helpicon,
  UserPlusIcon as Contactsicon,
  BanknotesIcon as Withdrawicon,
  DocumentIcon as Invoicesicon,
  Cog8ToothIcon as Settings,
  ArrowRightOnRectangleIcon as LogOuticon,
  ArrowDownTrayIcon as Download,
  MagnifyingGlassIcon as MagnifyingGlassIcon,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalIcon,
  ArrowsUpDownIcon as ArrowsUpDownIcon,
  UserCircleIcon as User,
  PaperAirplaneIcon as Send,
  EnvelopeIcon,
  PhoneIcon,
  CalendarIcon,
  UserIcon,
  MapPinIcon,
  TagIcon,
  
} from "@heroicons/react/24/outline";

export {
  CameraIcon,
  TagIcon,
  CalendarIcon,
  UserIcon,
  MapPinIcon,
  PhoneIcon,
  EnvelopeIcon,
  ErrorIconMini,
  CheckCircleIconMini,
  EyeIconMini,
  EyeSlashIconMini,
  ChevronLeftIconMini,
  ArrowUpTrayIconMini,
  XMarkIconMini,
  InformationCircleIconMini,
  InformationCircleIcon,
  CheckIconMini,
  PlusIcon,
  ChevronDownIcon,
  XMarkIcon,
  TrashIcon,
  PencilIcon,
  Homeicon,
  Helpicon,
  Contactsicon,
  Withdrawicon,
  Invoicesicon,
  Settings,
  LogOuticon,
  Download,
  User,
  Send,
  Plus,
  MenuBar,
  MagnifyingGlassIcon,
  AdjustmentsHorizontalIcon,
  ArrowsUpDownIcon,
};
